name: Java CI com Maven (SAM)

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    # Cria o banco de dados para os testes 
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root 
          MYSQL_DATABASE: sam_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v4

    - name: Configurar o JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: 'sam-api/pom.xml'

    - name: Compilar e testar com Maven
      working-directory: ./sam-api
      run: mvn -B clean package